import { Flex, Button, Stack } from "@chakra-ui/react";

import { Input } from "../components/Form/Input";

import Head from 'next/head'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Dashgo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Flex
        w="100vw"
        h="100vh"
        align="center"
        justify="center"
      >
        <Flex
          as="form"
          width="100%"
          maxWidth={360}
          bg="gray.800"
          p={8}
          borderRadius={8}
          flexDir="column"
        >
          <Stack spacing="4">
            <Input
              name="email"
              label="E-mail"
              type="email"
            />

            <Input
              name="password"
              label="Senha"
              type="password"
            />
          </Stack>

          <Button 
            type="submit"
            mt="6"
            colorScheme="pink"
            size="lg"
          >
            Entrar
          </Button>
        </Flex>
      </Flex>
    </div>
  )
}
